# Generated by Django 5.1.5 on 2025-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0003_orders_orderupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orderupdate",
            name="order_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
