# Generated by Django 5.1.5 on 2025-01-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0004_alter_orders_order_id_alter_orderupdate_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
