# Generated by Django 5.1.6 on 2025-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0005_alter_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderupdate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
