# Generated by Django 5.1.6 on 2025-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0006_alter_orderupdate_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
